version: '3'
services:
  yumrepo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.yumrepo
    volumes:
      - ./repo:/opt/pkg/repo
  debrepo-focal:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: focal
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=focal
  debrepo-jammy:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: jammy
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=jammy
  debrepo-buster:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: buster
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=buster
  debrepo-bullseye:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: bullseye
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=bullseye
  debrepo-debian:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: debian
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=debian
