version: '3'
services:
  yumrepo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.yumrepo
    volumes:
      - ./repo:/opt/pkg/repo
  debrepo-xenial:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: xenial
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=xenial
  debrepo-jessie:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: jessie
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=jessie
  debrepo-stretch:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: stretch
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=stretch
  debrepo-debian:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: debian
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=debian
