version: '3'
services:
  yumrepo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.yumrepo
    volumes:
      - ./repo:/opt/pkg/repo
  debrepo-bionic:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: bionic
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=bionic
  debrepo-xenial:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: xenial
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=xenial
  debrepo-focal:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: focal
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=focal
  debrepo-jessie:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: jessie
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=jessie
  debrepo-stretch:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: stretch
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=stretch
  debrepo-buster:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: buster
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=buster
  debrepo-bullseye:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: bullseye
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=bullseye
  debrepo-debian:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debrepo
      args:
        DIST: debian
    volumes:
      - ./repo:/opt/pkg/repo
    environment:
      - DIST=debian
