---
name: release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
    steps:
    - uses: actions/checkout@v3
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
        name: id_ed25519
        config: |
          Host sv13076.xserver.jp
            UserKnownHostsFile /dev/null
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/id_ed25519
    - name: dump keys
      run: |
        mkdir -p keys
        echo -n '${{ secrets.GPG_PUBLIC_KEY }}' > keys/pub.key
        echo -n '${{ secrets.GPG_SECRET_KEY }}' > keys/sec.key
    - name: deploy
      run: make deploy
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
